travis:
  secure:
    BINSTAR_TOKEN: H8w72UYs2UNdacBYr93lGKL8v/95y6Q/IsnTClMHlQ4mznh/MuEUYkJA5fPoDvd4wb769o6PYKq7zxzbeOZ74F2v0y2YuMd5wi3KpRDtDhxFlDjAb9nMwJU5PMdkb1M7z3nyIk1eXXJMZVkz5mQr1QDMSzYOi9o39MVJ6hH7e/3mmMWxwYSPWuMQVaWoERSNEiKagtjyoT9EFYhs97aw9hWXw8fulbLkcg3KBGOvXFZyMGinynVR/PIfDWofujw6jO0YYhQ9sWc1/UeDyFgQUAIyZKfW86qu9yxWLXnd/oj8IH+fPTboHJ5gUN1lVfqKgTNpZQPMwGDrieJFIIxXZ/0RK5hVnta0qv2q9K9BsyvmSYLGENgt6GlCwgEHstPUOq1z/mJhL+8sb2J6OdBopSif+pHw5b8rhdGkR/3zHzktqieKlqnBkjSSLeU3Y1hAa+RUOIvGo5FlI9KKdXXlKewiKtgCj31bQoGFHOqezYSd7BVmNLWGjFeQyvL1Q3sTTtAt76nBfgvqfPBlh0eK34WKcBWttzV2+omJfW5Hq86EHsfeKzFU0Eb2KGF+uKQyR8MJZLyvmUX8kRF1ahZl5L2YWwap2K6EZdkPnM45zh2llI0Hd7jOa35mLRE05nF7NXuWvXRe70b1tedP5rqHeoMt/Lc7rMQ5YRQEE7/ZTmo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
