travis:
  secure:
    BINSTAR_TOKEN: RpZEGNeJeBvDHVEh0Hj6VVC4Ew7Wti0RhyUzwyprRVl1pMpn8sg/DF+UGyLn1NQjj8I6XReWEcIogJF1fx6sFkv9qpTPTCUTtRJEkxK9OA888rb3qG/LyQWcTTfqP9P1ZN7yqKcoFBpskWpGR0ic6zM5fLz1wO3nlIUTQwBGJUVVlxe1+Myajd4OTHHLpOWPCC43QKY4dYjoUA7msHWKh21lYfrgrKq615/isez204CfqmLYcDEp4rYyUk5y8h4X7TdE3BVJK5itat49odux8/Gm1ubjzUSHe6arQVjczHQUqVCkYDCsM3pS/jknAGSBH7oAiEFmSeoAwGwc4WqNExyeq1vNoAlsjyIUGEA9LwzhuuJt2mbpk7ANQPlDBsgLuWoXuWIUXZpdUxAeHxykybfHAFv+6ZeN4v9TF6c0d5bOzcGvv9Gm31qUuTRVz6f1KdgVC4MRYBObhIGcxAzwoFIsPnnVAN32zqfk1NAbq5OEQAqtGX6JqgiNZ0eDXg9x1JSdon2JPRF55sD3YsrAEJtxF2MEj0I3JuVPbz6mTeGD9XEzR2kCpGOb4VVScLNZxf62iayqUH2NWV11QLczSTm5pAnoEiYMeGZFAjId+7+6RpJ32q5ERXnfeIW709vw7wYkA8JjZARgqMZTTlqqDxBirDlqa4/2UKTXFoBhqRM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
